# List of PR labels for readline

tags:
- internal/tag/*
commands:
- internal/gen/command*
flags:
- flags.go
- internal/parser/camelcase*
- internal/gen/flag*
positionals:
- internal/gen/positional*
- internal/positional/*
- internal/parser/positional/*
completions:
- internal/completions/*
options:
- internal/scan/options.go
scan:
- internal/parser.go
- internal/errors/errors.go
- internal/parser/parser_test.go
- internal/scan/*
validation:
- internal/validation/*
types:
- internal/convert/*
- internal/values/*
- internal/values/genvalues/*
- types.go
