name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go and tools
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.2

    - run: go install golang.org/x/tools/cmd/goimports@latest

    # Generate/check/format code
    - name: Generate and check
      run: go generate
    
    - name: Build
      run: go build -v ./...

    # Test and generate coverage
    - name: Test and coverage
      run: go test -race -coverprofile=coverage.txt

    - name: Upload coverage
      uses: codecov/codecov-action@v4

  windows:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go and tools
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.2

    - run: go install golang.org/x/tools/cmd/goimports@latest

    # Generate/check/format code
    - name: Generate and check
      run: go generate 

    - name: Build
      run: go build -v ./...
